### ISSUE TITLE
Cholmod error 'X and/or Y have wrong dimensions' at file ../MatrixOps/cholmod_sdmult.c, line 90

### ISSUE THREAD

**Issue by Derek-Jones** [DavidFirth/qvcalc#7]
The code:

```
p_mle = PlackettLuce(t, nspseudo=0)
...
t=qvcalc(p_mle)
```

Actual code+data here:
https://github.com/Derek-Jones/ESEUR-code-data/blob/master/reliability/educators.R

Produces the error:
Error in X %*% as.vector(coefs) : 
Cholmod error 'X and/or Y have wrong dimensions' at file ../MatrixOps/cholmod_sdmult.c, line 90

**Comment by DavidFirth** [comment]
Many thanks @Derek-Jones for reporting this.  The issue is not with `qvcalc`, but seems instead to be a bug in the PlackettLuce package.  So I have raised this there as an issue to solve: https://github.com/hturner/PlackettLuce/issues/42 .
